algolia/algoliasearch-sfcc-b2c

cartridges/int_algolia_sfra/cartridge/static/default/js/algolia/autocomplete-config.js
Added `objectID`, `queryID` and `indexName` to the URL of the PDP that opens when an Autocomplete result is clicked. This fixes the “Product Add to cart” event not being sent when the user navigates to the PDP from an Autocomplete result. Prior to this the event was sent only when the user was coming from an InstantSearch result.
In addition to this, I also added a new event that is sent when the user clicks an Autocomplete result (“Clicked on autocomplete product”), this was also missing previously.
=> APEX-177: Events not tracked when a search result is accessed from Autocomplete

cartridges/int_algolia_controllers/cartridge/static/default/js/algolia/autocomplete-config.js
Added the changes from #24 to the SiteGenesis cartridge as well.
> Added `objectID`, `queryID` and `indexName` to the URL of the PDP that opens when an Autocomplete result is clicked. This fixes the “Product Add to cart” event not being sent when the user navigates to the PDP from an Autocomplete result. Prior to this the event was sent only when the user was coming from an InstantSearch result.
>
> In addition to this, I also added a new event that is sent when the user clicks an Autocomplete result (“Clicked on autocomplete product”), this was also missing previously.
=> APEX-177: [SiteGenesis] Events not tracked when a search result is accessed from Autocomplete

cartridges/int_algolia_controllers/cartridge/static/default/js/algolia/insights-config.js, cartridges/int_algolia_sfra/cartridge/static/default/js/algolia/insights-config.js
Since SeachInsights v2 changed the default value of `useCookie` to `false`, a randomly-generated session-persistent userToken is no longer generated and saved to the `_ALGOLIA` cookie.
This also means that a `userToken` needs to be explicitly set in the code when `useCookie` is set to `false`, otherwise events without a `userToken` will not be forwarded and will raise an HTTP 422 error.
Added a page-persistent randomized userToken to each call in order to prevent the HTTP 422 errors.
=> APEX-156: User tracking improvements

cartridges/int_algolia/cartridge/scripts/algolia/model/algoliaProduct.js
Changed `in_stock` behavior to mirror SFCC's `product.availabilityModel.inStock` instead of relying on the threshold.
The old `in_stock` property calculation was flawed in that `product.availabilityModel.availability` would never be greater than `Algolia_InStockThreshold` and thus it would return `false` in each case.
=> in_stock behavior now reflects SFCC inStock

cartridges/int_algolia/cartridge/scripts/algoliaIngestionAPI.js
SFCC-58
This PR adds methods to to the Ingestion API Client introduced in #33, to be able to update the Data Ingestion objects:
- `updateAuthentication`
- `updateDestination`
I've also removed the usage of `.setThrowOnError()`, to rely directly on `result.ok`.
=> feat: add update methods to ingestion api service

cartridges/int_algolia/cartridge/scripts/algolia/model/algoliaProduct.js
- `in_stock` is now exported as true only if ATS is greater than or equal to `Algolia_InStockThreshold`
- removed explanatory comment
=> in_stock change

cartridges/int_algolia/cartridge/scripts/algolia/helper/jobHelper.js, cartridges/int_algolia/cartridge/scripts/algolia/steps/sendDeltaExportProducts.js, metadata/algolia/jobs.xml
Found a better way to handle attribute propagation to the variants when a master's attribute is changed (see #52 for the original PR).
There's a parameter that can be used to make the B2C delta export job add a master's variants to its output (via the `MasterProductExport` parameter of the `CatalogDeltaExport` system job step), so there's no need to handle this on our end by forcefully adding the variants of masters to the list of exported products.
The end result is the same, but this method should be a bit faster since we can eliminate one of the early `ProductMgr.getProduct()` calls to determine the master's variants.
Reverted most of the previous changes to `jobHelper` (from #52) since they are not needed anymore, except for the product filtering, which I moved to …
=> SFCC-123: Master attribute propagation improvement for AlgoliaProductsDeltaExport

.circleci/config.yml, cartridges/int_algolia/cartridge/scripts/algolia/helper/retryStrategy.js, cartridges/int_algolia/cartridge/scripts/algoliaIndexingAPI.js, cartridges/int_algolia/cartridge/scripts/services/algoliaIndexingService.js, jest.config.js, jest.setup.js, metadata/algolia/services.xml, package-lock.json, package.json, test/unit/int_algolia/scripts/algolia/algoliaIndexingAPI.test.js, test/unit/int_algolia/scripts/algolia/helper/retryStrategy.test.js
This PR introduce the Algolia indexing API client and its service:
- new `algolia.http.search.write` that has a higher timeout, and a dummy url
- new generic `algoliaIndexingService`, which accepts an object with the following parameters: `method`, `url`, `body`
- new API Client that exposes a single method for now: `sendBatch`, targeting the following endpoint: https://www.algolia.com/doc/rest-api/search/#batch-write-operations
The API Client doesn't call the service directly, it uses a `retryStrategy`:
The retry strategy is similar to the one present in Algolia's API clients and has been inspired by the retry strategies of the JavaScript and Go autogenerated API clients:
- A `StatefulHost` object will keep the state of each host. See …
=> feat: Algolia indexing client

cartridges/int_algolia/cartridge/scripts/algolia/steps/sendDeltaExportProducts.js
Made variable scoping tighter inside loops as the previous logic sent some products twice.
The "Products ready for update" metric in the Algolia BM module now displays the correct number of unique products (it included the duplicated records before).
This is just a performance improvement, data integrity had not been affected previously.
=> Delta Export improvements

cartridges/int_algolia/cartridge/scripts/services/algoliaServiceHelper.js
Removed a recurring message from job logs which doesn't hold any information:
`"Response is not JSON. Method: {0}. Result: {1}"`
Previously the code behaved as if it was expecting a JSON response from Stream and logged the above message otherwise. Since Stream doesn't return a JSON by default (only a 200 with an empty body), logging this message is not necessary.
The message will still be logged if there's a response body, but will be omitted if there isn't one.
=> Made job logs less noisy

cartridges/int_algolia/cartridge/scripts/algolia/customization/productModelCustomizer.js, cartridges/int_algolia/cartridge/scripts/algolia/model/algoliaLocalizedProduct.js, test/mocks/dw/catalog/Product.js, test/unit/int_algolia/scripts/algolia/model/algoliaLocalizedProduct.test.js, test/unit/int_algolia/scripts/algolia/model/algoliaProduct.js
SFCC-114
Introduce new product model: `AlgoliaLocalizedProduct`. This model is meant to be a final localized record ready to be indexed into Algolia.
It's a copy of the existing `AlgoliaProduct` with the following changes:
- The locale is set once and all properties are fetched with this single locale. For each attribute, instead an object of localized values, the properties now host the final value:
```diff
- { "name": { "default": "Dress", "en": "Dress", "fr": "Robe" } }
+ { "name": "Dress" }
```
- Hence, `getAttributeLocalizedValues()` has been removed
- Some values that were computed by the indexing pipeline are now computed by the model:
- `objectID`
- `__primary_category`: a `getPrimaryCategoryHierarchicalFacets()` methods builds [hierarchical …
=> feat: localized product model

cartridges/bm_algolia/cartridge/controllers/AlgoliaBM.js, cartridges/bm_algolia/cartridge/templates/default/algoliabm/dashboard/index.isml, cartridges/bm_algolia/cartridge/templates/resources/algolia.properties, cartridges/int_algolia/cartridge/scripts/algolia/lib/algoliaData.js, metadata/algolia/meta/system-objecttype-extensions.xml
The Read Host Base URL custom site preference (`Algolia_HostBase`) is not used for anything, the service URLs are stored in their respective service configurations.
=> SFCC-97: Removed Read Host Base URL custom site preference

cartridges/int_algolia/cartridge/scripts/algolia/helper/jobHelper.js, cartridges/int_algolia/cartridge/scripts/algolia/lib/algoliaData.js, cartridges/int_algolia/cartridge/scripts/algolia/steps/sendChunkOrientedProductUpdates.js, cartridges/int_algolia/cartridge/scripts/algoliaIndexingAPI.js, jest.setup.js, test/.eslintrc.json, test/mocks/global.js, test/unit/int_algolia/scripts/algolia/algoliaIndexingAPI.test.js, test/unit/int_algolia/scripts/algolia/steps/__snapshots__/sendChunkOrientedProductUpdates.test.js.snap, test/unit/int_algolia/scripts/algolia/steps/sendChunkOrientedProductUpdates.test.js
Update the `sendProductUpdates` job step to use the new model (https://github.com/algolia/algoliasearch-sfcc-b2c/pull/62) and the Algolia API client (https://github.com/algolia/algoliasearch-sfcc-b2c/pull/60), to push products records directly to Algolia.
- new `AlgoliaOperation` object, which match the payload expected by the Algolia batch API: https://www.algolia.com/doc/rest-api/search/#batch-write-operations-multiple-indices
- update `algoliaIndexingAPI` client, to be able to do multi-indices batch operations. This permits to have less logic in the job when we construct the batches
- update the `sendProductUpdates` job:
- the `process` function, for each Product, builds an array of `AlgoliaOperation` (one per locale), each targettng its own index name
- the `send` function concatenate …
=> feat: update sendProductUpdates job to direct indexing

cartridges/int_algolia/cartridge/scripts/algolia/lib/utils.js, cartridges/int_algolia/cartridge/scripts/algolia/model/algoliaLocalizedCategory.js, test/mocks/dw/catalog/Category.js, test/unit/int_algolia/scripts/algolia/model/algoliaLocalizedCategory.test.js
This PR introduces a "AlgoliaLocalizedCategory" model, similar to the "AlgoliaLocalizedProduct" model introduced in #62
There was no existing model for the categories, the objects were built directly by the job: https://github.com/algolia/algoliasearch-sfcc-b2c/blob/e2cf1ff8920fd3f92df4a815cbc6781291565a53/cartridges/int_algolia/cartridge/scripts/algolia/job/categoryIndexJob.js#L97
The work was to extract the code from the `categoryIndexJob` in order to create a standalone model, that we can test.
Note: the existing `prepareListOfCategories` method in the `categoryIndexJob` pushes objects in a global `listOfCategories`, containing all the categories objects to send. This will be the role of the new categories job that will be developed next. This PR is only defining the model of a single …
=> feat: introduce category model

cartridges/int_algolia/cartridge/scripts/algolia/helper/jobHelper.js, cartridges/int_algolia/cartridge/scripts/algolia/model/algoliaLocalizedProduct.js
Optimization on the way we generate the `__primary_category` field:
Instead of re-fetching the primary category hierarchy from the SFCC models, it now computes it from the `categories` field, that already contains all the hierarchies of all assigned categories of a product.
`npm run test:unit`
-> The expected final product object hasn't changed.
=> fix: compute hierarchical facets

cartridges/int_algolia/cartridge/scripts/algolia/job/sendCategories.js, cartridges/int_algolia/cartridge/scripts/algolia/lib/utils.js, cartridges/int_algolia/steptypes.json, jest.setup.js, test/mocks/dw/catalog/Category.js, test/mocks/dw/util/Collection.js, test/unit/int_algolia/scripts/algolia/job/__snapshots__/sendCategories.test.js.snap, test/unit/int_algolia/scripts/algolia/job/sendCategories.test.js
This PR introduce a new job step that exports all categories and send them to Algolia.
This job step follow the same logic than the current `categoryIndexJob` step:
- Iterate over the top categories: https://github.com/algolia/algoliasearch-sfcc-b2c/blob/c41b465530f93337d70986731f265661d1796d44/cartridges/int_algolia/cartridge/scripts/algolia/job/categoryIndexJob.js#L249
- For each, browse the subcategories in order to build objects ready to be indexed: https://github.com/algolia/algoliasearch-sfcc-b2c/blob/c41b465530f93337d70986731f265661d1796d44/cartridges/int_algolia/cartridge/scripts/algolia/job/categoryIndexJob.js#L97
The `prepareListOfCategories` function is now named `getSubCategoriesModels`. The differences are:
- It's pure: it returns an array with the categories object instead …
=> feat: categories direct indexing

cartridges/int_algolia/steptypes.json
Fixed `steptypes.json`, it now passes validation.
- changed `@description` to `description`
- removed `@trim` from the shared parameters
- added status codes for `custom.algoliaSendCategories` step
=> Fixed steptypes.json to pass validation

metadata/algolia/jobs.xml
`fullRecordUpdate` parameter has been removed from the job step in #70, but not from the `AlgoliaNewProductsDeltaExport` job declaration, resulting in the following error when trying to import the jobs:
```
[2023-10-02 16:58:44.575 GMT] INFO Import:  Start
[2023-10-02 16:58:44.575 GMT] INFO ImportFile:  operations/jobs.xml
[2023-10-02 16:58:44.575 GMT] INFO ImportMode:  REPLACE
[2023-10-02 16:58:44.575 GMT] INFO Starting Import of 'jobs' from: operations/jobs.xml
[2023-10-02 16:58:44.975 GMT] WARN [DATAERROR] [107/62] Job: AlgoliaNewProductsDeltaExport: Invalid job [AlgoliaNewProductsDeltaExport]! Invalid flow! Invalid step [algoliaSendChunkOrientedDeltaProductUpdates]! Invalid parameter [fullRecordUpdate]! Parameter is unknown and the step type …
```
=> fix(jobs.xml): replace `fullRecordUpdate` with `indexingMethod`

cartridges/int_algolia/cartridge/scripts/algolia/helper/reindexHelper.js, cartridges/int_algolia/cartridge/scripts/algolia/job/sendCategories.js, cartridges/int_algolia/cartridge/scripts/algolia/steps/sendChunkOrientedProductUpdates.js, cartridges/int_algolia/cartridge/scripts/algoliaIndexingAPI.js, cartridges/int_algolia/steptypes.json, jest.setup.js, metadata/algolia/jobs.xml, test/unit/int_algolia/scripts/algolia/algoliaIndexingAPI.test.js, test/unit/int_algolia/scripts/algolia/helper/reindexHelper.test.js, test/unit/int_algolia/scripts/algolia/job/__snapshots__/sendCategories.test.js.snap, test/unit/int_algolia/scripts/algolia/job/sendCategories.test.js, test/unit/int_algolia/scripts/algolia/steps/__snapshots__/sendChunkOrientedProductUpdates.test.js.snap, test/unit/int_algolia/scripts/algolia/steps/sendChunkOrientedProductUpdates.test.js
This PR adds the atomic reindexing logic to the `sendCategories` and `sendChunkOrientedProductUpdates` jobs.
An atomic reindex does the following:
- Delete any of the temporaries indices
- Index all products or categories into the temporary indices
- Copy the settings of the production indices on the temporary indices
- Move the temporary indices to production
- Added new methods to `algoliaIndexingAPI`:
- `deleteIndex`
- `copyIndexSettings`
- `moveIndex`
- `waitTask`, that continuously poll the Algolia tasks API until a task is processed, for a maximum of 5 min
- Created a `reindexHelper`, to perform the needed operations to Algolia based on the indexType (products or categories) and the available locales:
- delete the temporary indices
- copy the settings
- move the temporary indices
- …
=> feat: atomic reindexing

cartridges/int_algolia/cartridge/scripts/algolia/steps/sendChunkOrientedProductUpdates.js, cartridges/int_algolia/steptypes.json, metadata/algolia/jobs.xml, test/unit/int_algolia/scripts/algolia/steps/__snapshots__/sendChunkOrientedProductUpdates.test.js.snap, test/unit/int_algolia/scripts/algolia/steps/sendChunkOrientedProductUpdates.test.js
This PR cleans our jobs and steps definitions:
- remove legacy jobs to keep only the new jobs by default
- standardize the names and descriptions
Step names updated to:
- `custom.algoliaCategoriesIndex`
- `custom.algoliaProductsIndex`
- `custom.algoliaIndexDeltaProductUpdates`
Jobs name have now a `*Index_v2` suffix so they are clearly identified after importing the jobs, and don't overwrite legacy jobs.
- Some steps descriptions have been shortened, as the tooltip is hidden otherwise:
- The details of how each indexing mode works is moved to the `indexingMethod` parameter description, slightly shortened too:
- Removed some details about the implementation (chunk-based)
- Removed all legacy jobs and steps from the definitions
- Removed the `triggers`
---
SFCC-155
=> chore: default jobs names, descriptions and parameters

cartridges/int_algolia/cartridge/scripts/algolia/helper/reindexHelper.js, cartridges/int_algolia/cartridge/scripts/algolia/job/sendCategories.js, cartridges/int_algolia/cartridge/scripts/algolia/steps/sendChunkOrientedDeltaProductUpdates.js, cartridges/int_algolia/cartridge/scripts/algolia/steps/sendChunkOrientedProductUpdates.js, test/unit/int_algolia/scripts/algolia/helper/reindexHelper.test.js, test/unit/int_algolia/scripts/algolia/job/sendCategories.test.js, test/unit/int_algolia/scripts/algolia/steps/sendChunkOrientedDeltaProductUpdates.test.js, test/unit/int_algolia/scripts/algolia/steps/sendChunkOrientedProductUpdates.test.js
In a Algolia batch, if only a few records are in error, the whole batch is rejected.
To avoid rejecting a whole batch for a few faulty records, this PR introduces a helper that removes the records from the batch and retries to send it, when such error is detected.
- Put a description in on of your products that exceed the max record size limit
- Run the AlgoliaProductsIndex_v2 job
- In the logs, you will see something similar to:
```
[2023-10-11 09:47:31.346 GMT] ERROR CustomJobThread|522428417|AlgoliaProductsIndex_v2|algoliaProductsIndex {"message":"Record at the position 729 objectID=008884303996M is too big size=12822/10000 bytes. Please have a look at https://www.algolia.com/doc/guides/sending-and-managing-data/prepare-your-data/in-depth/index-and-records-size-and-usage-limitations/#re …
```
=> fix: retry batches without faulty records

cartridges/int_algolia/cartridge/scripts/algolia/helper/retryStrategy.js, cartridges/int_algolia/cartridge/scripts/algolia/steps/algoliaCategoryIndex.js
Our tests didn't detect it because they are run in a standard JS environment, but in an SFCC environment, `const` shouldn't be used inside `for` loops, because they have the following behaviour:
```
for (let i = 0; i < 3; ++i) {
const number = i;
Logger.info(number); // prints 0 three times
}
```
The result is that the retry strategy was calling 4 times the same host on the first request, then 4 times the same host one the second request, etc...
- Fixed the retry strategy loop
- Added more logs
- Change your Algolia app ID to an app ID that doesn't exist
- Trigger a v2 job
- Look at the logs, you will see all hosts being tried:
```
Request error on TESTAPP.algolia.net: ...
Marking host TESTAPP.algolia.net down.
Request error on TESTAPP-1.algolianet.com: ...
Marking host …
```
=> fix: retry strategy wasn't looping on all hosts

cartridges/bm_algolia/cartridge/controllers/AlgoliaBM.js, cartridges/int_algolia/cartridge/scripts/algolia/helper/sendHelper.js, cartridges/int_algolia/cartridge/scripts/algolia/job/sendCategoriesDelta.js, cartridges/int_algolia/cartridge/scripts/algolia/job/sendProductsDelta.js, cartridges/int_algolia/cartridge/scripts/algolia/steps/algoliaCategoryIndex.js, cartridges/int_algolia/cartridge/scripts/algolia/steps/algoliaProductDeltaIndex.js, cartridges/int_algolia/cartridge/scripts/algolia/steps/algoliaProductIndex.js, cartridges/int_algolia/cartridge/scripts/algolia/steps/sendDeltaExportProducts.js
Problem:
The `error` field of `dw.svc.Result` contains _"An error-specific code if applicable"_. The "if applicable" is important, as I found out that the error code can indeed be `0`, in case of DNS error for example. Here is the message I saw when putting a wrong App ID and running a job, produced by [this code](https://github.com/algolia/algoliasearch-sfcc-b2c/blob/2ff0b12b3722f54864f56b349b88978d76dee189/cartridges/int_algolia/cartridge/scripts/algolia/helper/retryStrategy.js#L119):
`Request error on TESTAPP.algolia.net: 0 - UnknownHostException:TESTAPP.algolia.net`
This means that all conditions testing `if (status.error)` are not behaving as expected when the error code is `0`.
Here is what happen for the `algoliaIndexProduct` job ran with a wrong app ID (the error happens when …
=> fix: network error handling

cartridges/int_algolia/cartridge/scripts/algolia/lib/algoliaProductConfig.js, cartridges/int_algolia/cartridge/scripts/algolia/model/algoliaLocalizedProduct.js, cartridges/int_algolia/cartridge/scripts/algolia/steps/algoliaProductDeltaIndex.js, cartridges/int_algolia/cartridge/scripts/algolia/steps/algoliaProductIndex.js, metadata/algolia/meta/system-objecttype-extensions.xml, metadata/algolia/sites/RefArch/preferences.xml, test/unit/int_algolia/scripts/algolia/model/algoliaLocalizedProduct.test.js, test/unit/int_algolia/scripts/algolia/steps/__snapshots__/algoliaProductDeltaIndex.test.js.snap, test/unit/int_algolia/scripts/algolia/steps/__snapshots__/algoliaProductIndex.test.js.snap, test/unit/int_algolia/scripts/algolia/steps/algoliaProductIndex.test.js
- Change the list of default attributes to the following, for v2 jobs:
`['name', 'primary_category_id', 'categories', 'url', image_groups, 'in_stock', 'price']`
I've also used the occasion to do the following optimizations:
- We were fetching the `CustomFields` property each time that we were instantiating the model. I've removed that from the model, which now requires the `fieldList` to be passed, so the list is built once at the beginning of the jobs (that's what the Delta job was already doing)
- since `id` is not in the default fields anymore, `_tags` are now added when the record will be fully replaced in the index
- Replaced the simple `concat()` by a loop that checks for duplicates, to avoid fetching a same field multiple times
---
SFCC-78
=> feat: update default attributes

cartridges/bm_algolia/cartridge/controllers/AlgoliaBM.js, cartridges/int_algolia/cartridge/scripts/algolia/helper/sendHelper.js, cartridges/int_algolia/cartridge/scripts/algolia/job/sendCategoriesDelta.js, cartridges/int_algolia/cartridge/scripts/algolia/job/sendProductsDelta.js, cartridges/int_algolia/cartridge/scripts/algolia/steps/algoliaCategoryIndex.js, cartridges/int_algolia/cartridge/scripts/algolia/steps/algoliaProductDeltaIndex.js, cartridges/int_algolia/cartridge/scripts/algolia/steps/algoliaProductIndex.js, cartridges/int_algolia/cartridge/scripts/algolia/steps/sendDeltaExportProducts.js
In #85 I fixed some checks involving `dw.svc.Result` objects.
We had named the variables `status`, which made me wrongly update all `status.error` checks to `!status.ok`.
But for the legacy jobs, the `status` variables were actually containing a `dw.system.Status` object, and those don't have a `ok` property.
This PR reverts them, and also rename the variables to `result` when the object is actually a `dw.svc.Result`.
=> fix: revert wrong checks on Status objects

cartridges/int_algolia/cartridge/scripts/algolia/lib/algoliaProductConfig.js, cartridges/int_algolia/cartridge/scripts/algolia/model/algoliaLocalizedProduct.js, cartridges/int_algolia/cartridge/scripts/algolia/steps/algoliaProductDeltaIndex.js, cartridges/int_algolia/cartridge/scripts/algolia/steps/algoliaProductIndex.js, cartridges/int_algolia/steptypes.json, test/unit/int_algolia/scripts/algolia/steps/__snapshots__/algoliaProductDeltaIndex.test.js.snap, test/unit/int_algolia/scripts/algolia/steps/__snapshots__/algoliaProductIndex.test.js.snap
The `image_groups` attribute was marked as non-localized in the `attributeConfig`.
To avoid adding yet another exception in the jobs code (it's also the case for `categories`), I've created a new `attributeConfig_v2`, which is a copy of the `attributeConfig` with the following modifications:
- `categories` and `image_groups` are set to `localized: true`
- properties are ordered alphabetically (first the ones with an `attribute` declared, then the others)
---
Unrelated small change: one of the job steps description was too large for the BM tooltip, I've shortened it.
---
SFCC-179
=> fix: localized image_groups

cartridges/int_algolia/cartridge/scripts/algolia/steps/algoliaCategoryIndex.js, cartridges/int_algolia/cartridge/scripts/algolia/steps/algoliaProductDeltaIndex.js, cartridges/int_algolia/cartridge/scripts/algolia/steps/algoliaProductIndex.js, cartridges/int_algolia/steptypes.json, test/unit/int_algolia/scripts/algolia/steps/algoliaProductIndex.test.js
For some errors, we were immediately throwing an error to mark the job as failed, without writing the report object. So they were not logged in the Business Manager.
- Set `jobReport.error` and `jobReport.errorMessage` when we encounter some error but don't throw immediately
- Then:
- If the error happens early: write the report object and throw
- If the error happens at the end of the job: write the report object and rely on the `jobReport.error` field to mark the job as success or to throw the error
- Set wrong Algolia credentials
- Run the AlgoliaProductIndex_v2 job
- Error should be reported in the BM:
---
SFCC-179
=> fix: some errors were missing in BM reporting

cartridges/int_algolia/cartridge/scripts/algolia/steps/algoliaProductDeltaIndex.js, test/mocks/dw/catalog/Product.js
Our indexing jobs rely on `queryAllSiteProducts()`, which return only the products assigned to the site.
The Delta job wasn't taking that into account, if a product was unassigned from all categories, it was still updated instead of being deleted.
The product object has a `isAssignedToSiteCatalog()` method that permits to fix this behaviour.
---
SFCC-179
=> fix: delta job wasn't deleting unassigned products

cartridges/int_algolia/cartridge/scripts/algolia/steps/algoliaProductDeltaIndex.js, jest.setup.js
I've tried to change the `consumer` or `deltaExportJobName` parameters at the step level (`algoliaProductDeltaIndex`)
This threw the following error when trying to call `deltaExportZips.forEach`: 
```
com.demandware.core.script.capi.ScriptingException: TypeError: Cannot call method "forEach" of undefined (int_algolia/cartridge/scripts/algolia/steps/algoliaProductDeltaIndex.js#333)
at int_algolia/cartridge/scripts/algolia/steps/algoliaProductDeltaIndex.js:333 (anonymous)
Caused by: com.demandware.core.script.capi.ScriptingException: TypeError: Cannot call method "forEach" of undefined (int_algolia/cartridge/scripts/algolia/steps/algoliaProductDeltaIndex.js#333)
```
I understand that we don't want to mark the job as error, because it can be normal that the directory doesn't exist. So:
- …
=> chore: minor changes in delta export job

cartridges/bm_algolia/cartridge/controllers/AlgoliaBM.js, cartridges/bm_algolia/cartridge/templates/default/algoliabm/dashboard/index.isml, cartridges/int_algolia/cartridge/scripts/algolia/lib/algoliaData.js, cartridges/int_algolia/cartridge/scripts/algolia/steps/algoliaProductDeltaIndex.js, cartridges/int_algolia/cartridge/scripts/algolia/steps/algoliaProductIndex.js, cartridges/int_algolia/steptypes.json, jest.setup.js, metadata/algolia/jobs.xml, metadata/algolia/meta/system-objecttype-extensions.xml, metadata/algolia/sites/RefArch/preferences.xml, test/unit/int_algolia/scripts/algolia/model/algoliaLocalizedProduct.test.js, test/unit/int_algolia/scripts/algolia/steps/algoliaProductIndex.test.js
The ID of the `CustomFields` site preference needs to be changed in order to minimize the possibility for errors upon upgrading, since the list of default + recommended additional attributes has changed.
Renamed site preference `CustomFields` to `AdditionalAttributes`.
Old jobs and scripts still use `CustomFields` as it won't be removed forcibly from the cartridge with `mode="delete"`, but I'll mention it in the release notes so that clients who want to fully transition to the new jobs can remove it.
Getter methods in `algoliaData` will no longer throw an error when trying to get preferences which have not been defined in BM (`Cannot read property "length" from null` error).
=> Changed Algolia_CustomFields to Algolia_AdditionalAttributes

cartridges/int_algolia/cartridge/scripts/algoliaExportAPI.js
There was a syntax error which resulted in OCAPI password being `null` when `Algolia_OCAPIClientPassword` wasn't defined, instead of taking the default `'aaaaaaaaaaaaaaaaaaaaaaa'` value.
=> fix: ocapi default pwd

cartridges/int_algolia/cartridge/scripts/algolia/steps/algoliaProductDeltaIndex.js, cartridges/int_algolia/cartridge/scripts/algolia/steps/algoliaProductIndex.js, cartridges/int_algolia/steptypes.json, test/unit/int_algolia/scripts/algolia/steps/algoliaProductDeltaIndex.test.js, test/unit/int_algolia/scripts/algolia/steps/algoliaProductIndex.test.js
New job step parameter: `failureThresholdPercentage`
When the percentage of records that failed to be indexed exceeds this threshold, the jobs are marked in error.
In case of failure:
- For a `fullCatalogReindex`, the temporary indices are not moved.
- For a delta export job, the delta export zips are not moved.
- For other jobs, the job is only reported in error
---
SFCC-168
=> feat: failureThresholdPercentage parameter

cartridges/int_algolia/cartridge/scripts/algolia/helper/ssrHelper.js, cartridges/int_algolia/cartridge/scripts/algolia/lib/algoliaProductConfig.js
I got the following error when enabling SSR on a sandbox with CM 21.7:
```
SyntaxError: invalid object initializer
in controller Search
```
Small unrelated changed: moved the `in_stock` declaration to the 2nd section and removed the `attribute` field, as it's handled by a custom function
=> chore: make SSR work with compatibility mode 21.7 and below

cartridges/int_algolia/cartridge/scripts/algolia/customization/productModelCustomizer.js
In older Compatibility Mode versions, the jobs are throwing the following error:
`TypeError: Cannot find function includes in object primary_category_id,in_stock,price. (int_algolia/cartridge/scripts/algolia/customization/productModelCustomizer.js#108)`
Use `indexOf` instead of `includes` to make it compatible.
Tested on CM 18.10.
=> fix: productModelCustomizer compatibility mode

cartridges/int_algolia/cartridge/scripts/algolia/helper/reindexHelper.js, cartridges/int_algolia/cartridge/scripts/algolia/steps/algoliaCategoryIndex.js, cartridges/int_algolia/cartridge/scripts/algolia/steps/algoliaProductIndex.js, cartridges/int_algolia/cartridge/scripts/algoliaIndexingAPI.js, test/unit/int_algolia/scripts/algolia/algoliaIndexingAPI.test.js, test/unit/int_algolia/scripts/algolia/helper/reindexHelper.test.js, test/unit/int_algolia/scripts/algolia/steps/algoliaCategoryIndex.test.js, test/unit/int_algolia/scripts/algolia/steps/algoliaProductIndex.test.js
The [copy settings](https://www.algolia.com/doc/rest-api/search/#copymove-index) behaviour is slightly different between Algolia's Classic and the newer engine:
When copying index settings from a source index that doesn't exist, the engine returns a `taskID` in both cases. But:
- On Classic, this taskID was immediately marked as `published`
- On the newer infra, this taskID will never be marked as `published`, the engine considers that there is nothing to do so it doesn't "publish" anything
The cartridge was relying on the former behaviour, and the `finishAtomicReindex` method was systematically doing a `copyIndex` and then wait for the task to complete, even in the case of a first `fullCatalogReindex`, where the production index doesn't exist yet.
So on the newer infra, the `waitTask` …
=> fix: copy index settings

cartridges/int_algolia/cartridge/templates/default/algolia/headerScripts.isml, cartridges/int_algolia_sfra/cartridge/static/default/js/algolia/insights-config.js, cartridges/int_algolia_sfra/cartridge/templates/default/algolia/insights.isml
Send [`purchasedObjectIDs` events](https://www.algolia.com/doc/api-reference/api-methods/purchased-object-ids/)
The event is sent when the user reaches the `Order-Confirm` step.
We can detect that because this endpoint is the only place that sets `pdict.orderUUID`: [see Order.js#L87](https://github.com/SalesforceCommerceCloud/storefront-reference-architecture/blob/dec9c7c684275127338ac3197dfaf8fe656bb2b7/cartridges/app_storefront_base/cartridge/controllers/Order.js#L87)
A new `<span>` dedicated to Algolia Insights has been introduced.
When `pdict.orderUUID` is present, the span will keep the `order` in its `data-order` property. The Insights library relies on its presence to send the purchase event.
(The span will also be used to hold the userToken)
To test without having to complete the …
=> feat(insights): send purchasedObjectIDs events

cartridges/int_algolia_sfra/cartridge/static/default/js/algolia/insights-config.js, cartridges/int_algolia_sfra/cartridge/templates/default/algolia/insights.isml
ISML gives access to the `dw.system.Session`
We can leverage the recently introduced `algolia-insights` span to expose the authenticated user token and pass it to the `authenticatedUserToken` parameter of the insights library.
The `userToken` is set using the `dwanonymous_` cookie exposed by the platform.
This permits to have both tokens in parallel and ensure continuity when the user logs in.
- Open a CLP
- a `Hits Viewed` event is sent to the insights API with only the `userToken`. The value match the value of the `dwanonymous_` cookie
- Log in
- Go to a CLP
- a `Hits Viewed` event is sent with the same `userToken` and a `authenticatedUserToken`
---
SFCC-199
=> feat(insights): set user tokens

metadata/algolia/meta/system-objecttype-extensions.xml
System Object types definitions have been broken in #110
Trying to import them result in the following error:
> ERROR [144|33] cvc-complex-type.2.4.d: Invalid content was found starting with element 'mandatory-flag'. No child element is expected at this point.
It turns out that the `default-value` is apparently expected at the end.
Also quick question: why has it been marked as mandatory in the definition? It's not marked as mandatory in the UI, and since it's a number, it defaults to 0.0 in any case I think?
=> fix: system object definitions

cartridges/int_algolia/cartridge/scripts/algolia/helper/reindexHelper.js
The Batch API response when some records are refused by the engine is different on the new Algolia infra:
- It previously had a `objectID` field to identify the faulty record
- The `message` field is slightly different
This PR updates the logic that identifies and removes faulty records from a batch:
- If the payload contains the `objectID` field, we still rely on it
- Otherwise, if the message contains `is too big`, we use a regex to extract the faulty objectID
@htuzel if you want to test I've invited you to the "Ingestion test" app that runs on the new infra.
- Modify the cartridge to generate a big record for one of the products. To do so, I've added the following code to the `customizeLocalizedProductModel()` function, that sets 100KB of text in a `test` attribute, for product …
=> fix: retry batch strategy

cartridges/int_algolia_controllers/cartridge/static/default/js/algolia/index.js, cartridges/int_algolia_controllers/cartridge/static/default/js/algolia/insights-config.js
I've tested more the SiteGenesis cartridge and realized that what we did on SFRA for the userTokens in #115 is also valid on SiteGenesis:
- the `<span id="algolia-insights"` is present in the frontend
- the `dwanonymous_` cookie is also exposed by the platform.
- Set userToken and authenticatedUserToken the same way we did in #115.
- Fix: we weren't checking `algoliaData.enableInsights` before calling `enableInsights()`
- Chore: pass the default `productsIndex` to `enableInsights()`
---
SFCC-227
=> fix(sg): set insights user token and rely on enableInsights param

.github/workflows/release.yml
Our current release flow is too manual and error prone (cf #123).
This PR introduces a GitHub workflow to handle it. It will:
- Checkout the project
- Merge the `develop` branch into `master`
- Draft a new release
After the workflow is merged, the release flow will become:
- Create a PR to bump the version number and write a changelog
- Merge the PR on `develop`
- Go into **Actions > Draft release** and trigger the release workflow [manually](https://docs.github.com/en/actions/using-workflows/manually-running-a-workflow) (The version/tag name is a required parameter)
- Go in the [Releases](https://github.com/algolia/algoliasearch-sfcc-b2c/releases) section to edit the draft and publish it
I've tested the workflow on a private repo so I couldn't test how it behaves with branches …
=> chore: introduce release workflow

cartridges/int_algolia/cartridge/scripts/algolia/steps/algoliaProductIndex.js, test/unit/int_algolia/scripts/algolia/steps/algoliaProductIndex.test.js
When sending an empty batch of records, the `taskID` field of the Algolia response is set to `0` instead of an object:
`{"taskID":0,"objectIDs":[]}`
As the cartridge expects an object and tries to iterate on the taskIDs (using `Object.keys()`), sending an empty batch was generating an error.
- Don't send batches of 0 records
Temporarily change the `isInclude()` method of the [`productFilter`](https://github.com/algolia/algoliasearch-sfcc-b2c/blob/master/cartridges/int_algolia/cartridge/scripts/algolia/filters/productFilter.js) to `return false;` and run the AlgoliaProducIndex_v2 job.
=> fix: don't send empty batches

cartridges/int_algolia/cartridge/scripts/algolia/helper/reindexHelper.js, test/unit/int_algolia/scripts/algolia/helper/reindexHelper.test.js
For reasons detailed in #114, we can't do a [`copyIndex`](https://www.algolia.com/doc/rest-api/search/#copymove-index) without checking first if the index exists on Algolia's newer engine.
To check if an index exist, the common way is to do a [`getSettings`](https://www.algolia.com/doc/rest-api/search/#get-settings) on it.
Since a `getSettings` returns the index settings, I used the response to then call `setSettings`.
The problem with that approach is that it copies only the settings, while the `copyIndex` endpoint also copies Rules and Synonyms.
- Still check if the index exists with a `getSettings` call, but use the `copyIndex` endpoint to actually do the settings copy.
=> fix: partially revert #114 and use 'copyIndex' to copy index settings

cartridges/int_algolia/cartridge/scripts/algolia/steps/algoliaContentIndex.js, cartridges/int_algolia/steptypes.json, metadata/algolia/jobs.xml
- Just changed variable name from `delimiterTag` to `splittingTag` to make it more clear
=> fix: naming convention for splittingTag

cartridges/int_algolia/cartridge/scripts/algoliaIndexingAPI.js
Search clusters can sometimes experience exceptional load, resulting in some indexing operations taking more than 5 minutes to complete.
Let's increase the `waitTask` timeout to avoid having the job failing in those cases.
---
CR-5491
=> fix: increase waitTask timeout

cartridges/int_algolia_sfra/cartridge/static/default/js/algolia/instantsearch-config.js
I had forgotten to adjust the `price` facet in #135:
For the master-level records, the price is located in the `variants.price` attribute by default.
=> chore: fix price facet

cartridges/int_algolia/cartridge/scripts/algolia/lib/algoliaSplitter.js, cartridges/int_algolia/cartridge/scripts/algolia/lib/contentUtil.js, cartridges/int_algolia/cartridge/scripts/algolia/model/algoliaLocalizedContent.js, cartridges/int_algolia/cartridge/scripts/algolia/steps/algoliaContentIndex.js, jest.setup.js, test/unit/int_algolia/scripts/algolia/lib/__snapshots__/contentUtil.test.js.snap, test/unit/int_algolia/scripts/algolia/lib/algoliaSplitter.test.js, test/unit/int_algolia/scripts/algolia/lib/contentUtil.test.js
Replaced ```$url(), $httpUrl(), $httpsUrl()``` with SFCC rendered values
- Handled dynamic content values for both content asset and page designer pages
- Created a hard-coded configuration
- Wrote unit tests
- Enable hardcoded `enableContentFunctionHandler` config in `cartridges/int_algolia/cartridge/scripts/algolia/lib/contentUtil.js`
- Add following content to any content asset and check index on Algolia
```
<h1>---TESTS---</h1>
<div>
URL:
<a title="My URL Search Link" target="_new" href="$Url('Search-ShowContent', 'q', 'customer')$"><span>URL Search
Link Content Asset Link </span></a>
<p>XXXXX$Url('Search-ShowContent', 'q', 'customer')$XXXX</p>
</div>
<div>
HTTP
XXXXX$httpUrl('Search-Show', 'cgid', 'J','psortb1','category-pos_J')$XXXX
</div>
<div>
HTTPS
XXXX$httpsUrl('Search-Show', …
```
=> feat: Handling Dynamic content Values

cartridges/int_algolia/cartridge/scripts/algolia/customization/productModelCustomizer.js, cartridges/int_algolia_controllers/cartridge/static/default/js/algolia/instantsearch-config.js, cartridges/int_algolia_sfra/cartridge/static/default/js/algolia/instantsearch-config.js, test/unit/int_algolia/scripts/algolia/customization/productModelCustomizer.test.js
- The category attribute name has been updated from 'CATEGORIES_NEW_ARRIVALS' to 'newArrivals'.
- Nonapplicable hierarchical facets have been hidden.
- Add the `newArrivals` attribute to `AdditionalAttributes`.
- Create a facet for it on the Algolia Dashboard.
=> SFCC-284 | Newarrivals Refactoring

cartridges/bm_algolia/cartridge/templates/default/algoliabm/dashboard/index.isml, cartridges/int_algolia/cartridge/scripts/algolia/helper/jobHelper.js, cartridges/int_algolia/cartridge/scripts/algolia/model/algoliaLocalizedProduct.js, cartridges/int_algolia_sfra/cartridge/static/default/js/algolia/instantsearch-config.js, jest.setup.js, test/mocks/dw/catalog/Variant.js, test/unit/int_algolia/scripts/algolia/model/algoliaLocalizedProduct.test.js
Add a new `pricebooks` field declaration. When used, it will add all prices from available pricebooks to the records, for each enabled currency:
```json
{
"pricebooks": {
"USD": {
"price": 10,
"pricebookID": "sale-prices",
"onlineFrom": 0,
"onlineTo": 3155760000000,
}
}
}
```
When present in the records, the default UI will use it to display the strikeout price:
Our default UI display a strikeout price when we have a `price` and a `promotionalPrice`. If we have a price higher than the actual `price` in the pricebooks
**note**: This only works for Variation Level record model. We indeed don't have a way to configure which fields should go in the `variants` objects for the "Base Level" record model currently.
- Added unit tests
- note: fixed a small mistake in our tests. …
=> feat: multiple pricebooks

cartridges/int_algolia_sfra/cartridge/static/default/css/algolia/index.css, cartridges/int_algolia_sfra/cartridge/static/default/js/algolia/instantsearch-config.js, cartridges/int_algolia_sfra/cartridge/templates/default/algolia/search/searchResultsNoDecorator.isml
If you trigger a search using Autocomplete (and hitting the enter key), results are displayed using InstantSearch.
You can refine using facets, but you can’t clear the current query because the searchBox is hidden. To update/clear the query, you have to do a new search from Autocomplete, which is not obvious.
This PR makes the searchbox visible:
- Trigger a search using Autocomplete
- The query will be visible in the searchbox and you can update it
---
SFCC-263
=> feat: show searchbox

cartridges/int_algolia/cartridge/scripts/algolia/helper/jobHelper.js, cartridges/int_algolia/cartridge/scripts/algolia/lib/algoliaProductConfig.js, cartridges/int_algolia/cartridge/scripts/algolia/steps/algoliaProductDeltaIndex.js, cartridges/int_algolia/cartridge/scripts/algolia/steps/algoliaProductIndex.js
In the Variant-level record model, there can be "siblings" data in each records. For example for the color swatches, every variant record has a `colorVariations` field, containing all available color variations of the master product.
For optimization purposes, we want to compute those fields only once for each master product and inject it in each variants.
This PR introduces a new `computedFromBaseProduct` configuration parameter.
When some attributes are declared with `computedFromBaseProduct: true`:
- the jobs do the indexing based on the master product (before it was the case only for the hardcoded `colorVariations` attribute)
- the `generateVariantRecords()` method compute those attributes only once, and inject it into each variant
---
SFCC-298
=> feat: new 'computedFromBaseProduct' attribute configuration

cartridges/int_algolia_sfra/cartridge/static/default/js/algolia/recommend-config.js
- Used another attribute for displaying prices to prevent calculations/renderings side effect on the original attribute.
**Root Cause:** It seems that the itemComponents function is being called twice, even though we only created the widget once.
By the way, I spent a lot of time investigating an issue but couldn't why the root cause is happening. I even asked for assistance on Stack Overflow teams from recommend team, but they couldn't understand the issue. I eventually found a workaround. @sbellone, if you have any ideas about this mysterious bug, please let me know. This pull request is just a suggestion to address the issue.
[Question and screenshots for the bug is here](https://stackoverflowteams.com/c/algolia/questions/6278)
- [Train Recommendation Models …
=> Fixing pricing re-rendering issue by using another attribute for displaying prices

cartridges/int_algolia/cartridge/scripts/algolia/recommend/utils.js, jest.setup.js, test/unit/int_algolia/scripts/algolia/recommend/utils.test.js
- Refactoring the getMasterProductIds function to use the getProductType function
- Adding the getProductType and getAppropriateProduct functions
- Updating the getAnchorProductIds function to use the getProductType and getAppropriateProduct functions
- Added unit tests
These changes improve the logic for getting master product IDs and anchor product IDs in the Algolia recommend feature.
See how it works for variant and base model indexing for the following products: (adjust URL for your sandbox)
- https://zzgk-004.dx.commercecloud.salesforce.com/s/RefArch/3/4-sleeve-v-neck-top/25519318M.html?lang=en_US
- https://zzgk-004.dx.commercecloud.salesforce.com/s/RefArch/3/4-sleeve-v-neck-top/25519318M.html?lang=en_US
- https://zzgk-004.dx.commercecloud.salesforce.com/s/RefArch/mens-basic-leg-trou …
=> Dynamic logic for handling different product types and and index models

cartridges/int_algolia/cartridge/scripts/algolia/steps/algoliaCategoryIndex.js, test/unit/int_algolia/scripts/algolia/steps/__snapshots__/algoliaCategoryIndex.test.js.snap
The categories job was sending one Algolia batch for each top-level category, with all locales:
We were iterating only once on each top level category, and fetching all sub-categories of all locales.
Top-level categories can contain a big amount of sub-categories. Combined with a big amount of locales, this could lead to a batch too big to fit in SFCC limitations (20000 objects in an array).
This PR invert the loops. We will now:
- Iterate on each locale
- For each locale, iterate on each top-level category and build a complete batch for this locale
- Send the batch and continue with the next locale
This will permit the category job to support up to 20000 categories.
Run the categories job in a new index.
Index content should be identical to an index generated with the previous version.
=> fix(categories): split batches by locale

cartridges/int_algolia/cartridge/scripts/algolia/helper/modelHelper.js
The code changes in `modelHelper.js` introduce logic to handle PWA variant ID in color variations. The `IS_PWA` flag is used to determine if the variant ID should be included in the color variations object. This change improves the functionality for PWA users.
=> feat: Add logic to handle PWA variant ID in color variations

cartridges/int_algolia/cartridge/scripts/algolia/steps/algoliaCategoryIndex.js, cartridges/int_algolia/cartridge/scripts/algolia/steps/algoliaContentIndex.js, cartridges/int_algolia/cartridge/scripts/algolia/steps/algoliaProductIndex.js
I've reproduced the OOM error. My findings:
- First, we unfortunately can't catch it and give a proper explanation. It's a Java error not sent back to our JavaScript code. Below is my repro code. The exception never passes in the `catch` block.
- Another problem I found is that the `afterStep` part of our job was still trying to finish the indexing even when `success` is false :confused: . So it moves the temporary indices to production even if not all products have been processed.
This PR fixes the `afterStep`: don't try to complete the reindex in case of previous errors (i.e. when `success` is `false`).
I've also added a preventive `try/catch` around the sending of the batch. As I said, it doesn't catch the OOM error, but it still may catch other issues we haven't thought about.
- Apply …
=> fix: abort afterStep in case of previous errors

cartridges/int_algolia/cartridge/scripts/algoliaSearchAPI.js
The code changes in `algoliaSearchAPI.js` add additional SSR params to the Algolia search API request. This includes setting the `hitsPerPage` to 9 and disabling analytics. This change improves the server-side rendering performance for search results.
=> feat: Add additional SSR params for Algolia search API

cartridges/int_algolia/cartridge/scripts/algolia/helper/AlgoliaJobReport.js, cartridges/int_algolia/cartridge/scripts/algolia/steps/algoliaCategoryIndex.js, cartridges/int_algolia/cartridge/scripts/algolia/steps/algoliaContentIndex.js, cartridges/int_algolia/cartridge/scripts/algolia/steps/algoliaProductDeltaIndex.js, cartridges/int_algolia/cartridge/scripts/algolia/steps/algoliaProductIndex.js, cartridges/int_algolia/steptypes.json, test/unit/int_algolia/scripts/algolia/steps/algoliaCategoryIndex.test.js, test/unit/int_algolia/scripts/algolia/steps/algoliaProductDeltaIndex.test.js, test/unit/int_algolia/scripts/algolia/steps/algoliaProductIndex.test.js
Add a new `localesForIndexing` parameter at the job step level for all our jobs.
Our jobs will now use the locales from:
- This new `localesForIndexing` parameter in priority
- The `Algolia_LocalesForIndexing` custom preference if the job level parameter is empty
- The locales enabled on the Site if both parameters are empty
- Small fix added to the `AlgoliaJobReport.formatCustomObject` function: it could throw an exception when no `endDate` was defined, causing a crash on the BM:
```
com.demandware.core.script.capi.ScriptingException: Wrapped java.lang.NullPointerException (int_algolia/cartridge/scripts/algolia/helper/AlgoliaJobReport.js#88)
at int_algolia/cartridge/scripts/algolia/helper/AlgoliaJobReport.js:88 (anonymous)
at bm_algolia/cartridge/scripts/helper/BMHelper.js:35 (anonymous) …
```
=> feat: localesForIndexing parameter at job level

cartridges/int_algolia_sfra/cartridge/controllers/Search.js
When we use Algolia, we do not need a personalized cache because the SSR result always will be same and we will fetch the results in the frontend. It will improve caching performance.
=> Cache Strategy Improved

cartridges/int_algolia/cartridge/templates/default/algolia/insights.isml, cartridges/int_algolia_sfra/cartridge/controllers/Cart.js, cartridges/int_algolia_sfra/cartridge/controllers/Order.js, cartridges/int_algolia_sfra/cartridge/static/default/js/algolia/insights-config.js
- Fixed Record model event issue (Logic moved to controllers)
- Used master product id for base model record dynamically
- Fixed Purchase event issue
- order object had missing attributes and it is calculated on the backend and sent to frontend (`order.items.items` don't have a `price` property)
- Fixed lastQuery logic (for `undefined` cases)
- When we land to PDP, and there is no lastQuery, we were sending it as `undefined` and it was causing 422 error on Algolia side
I also added some comments on the [Jira ticket](https://algolia.atlassian.net/browse/SFCC-367?atlOrigin=eyJpIjoiMGE0NzExZWUwMDVjNDY2MjliM2IxMTg3NmU3MTAxYTkiLCJwIjoiaiJ9), please let me know what do you think about it?
=> bugfix: Fixed Event issues for Base and Variant Record Models

cartridges/int_algolia/steptypes.json
Update the timeout-in-seconds value for Algolia job steps to 3600 seconds (Max value for each script). This change ensures that the job steps have sufficient time to complete without timing out.
=> Increase default job timeouts

cartridges/int_algolia/cartridge/scripts/algolia/helper/jobHelper.js, cartridges/int_algolia/cartridge/scripts/algolia/model/algoliaLocalizedProduct.js, cartridges/int_algolia/cartridge/scripts/algolia/model/algoliaProduct.js, cartridges/int_algolia/cartridge/scripts/algolia/steps/algoliaProductDeltaIndex.js, cartridges/int_algolia/cartridge/scripts/algolia/steps/algoliaProductIndex.js, test/mocks/dw/catalog/Variant.js, test/unit/int_algolia/scripts/algolia/model/algoliaLocalizedProduct.test.js
- feat: Add logic to handle custom and activeData values without any code changes with some default values. We can still use Extension mechanism for customization
- Added grouping mechanism for nested objects
Unit tests are extended
- Create a new localized custom attribute in your sandbox (I created in 003 is named `algoliaTest`, and feel free to use it)
- Add it in indexable attributes like custom.algoliaTest
- See it in your index
- You can also change some locale name and try to override and observe different results
=> Remove constraint to have to declare attributes

cartridges/int_algolia/algoliaconfig.json, cartridges/int_algolia/cartridge/scripts/algoliaIndexingAPI.js
We've increased the total job steps timeouts in #181, but some individual tasks can take more than 10 minutes to complete.
This PR makes the `waitTask` timeout configurable and sets the default to 30 min.
=> feat: configurable waittask timeout

cartridges/bm_algolia/cartridge/templates/default/algoliabm/dashboard/index.isml, cartridges/bm_algolia/cartridge/templates/resources/algolia.properties, metadata/algolia/meta/system-objecttype-extensions.xml
Since 23.5.0, the `Algolia_Enable` setting is only used by the Storefront.
This PR renames its label and description and move it below, next to all the Storefront checkboxes.
Also, other checkboxes that enable Storefront features are now disabled when `Algolia_Enable` is not checked, to make it clear that they are linked to the Storefront.
=> chore: rename Algolia_Enable description and move it below

cartridges/int_algolia/cartridge/scripts/algolia/helper/objectHelper.js, cartridges/int_algolia/cartridge/scripts/algolia/model/algoliaLocalizedProduct.js, test/mocks/dw/catalog/Variant.js, test/unit/int_algolia/scripts/algolia/helper/objectHelper.test.js, test/unit/int_algolia/scripts/algolia/model/algoliaLocalizedContent.test.js, test/unit/int_algolia/scripts/algolia/model/algoliaLocalizedProduct.test.js, test/unit/int_algolia/scripts/algolia/steps/algoliaProductDeltaIndex.test.js, test/unit/int_algolia/scripts/algolia/steps/algoliaProductIndex.test.js
This PR implements the improvement suggested here: https://github.com/algolia/algoliasearch-sfcc-b2c/pull/182#discussion_r1711608099:
- Introduce a `objectHelper.setAttributeValue()` function, that permits to set a nested attribute to an object
- Use those generic `ObjectHelper.getAttributeValue` / `ObjectHelper.setAttributeValue` in the model instead of manually manipulating `parentAttribute`/`subAttribute`
This permits to simplify the logic and support any level of nesting.
Unit:
- Added tests for the `setAttributeValue()` method
- Added tests for the `algoliaLocalizedProduct` model that use a deeply nested property (`custom.deeply.nested`)
- All existing tests are passing
(I've removed the multiple mocks of `*/cartridge/scripts/algolia/helper/objectHelper` as it's defined in …
=> feat: default attribute config for any level

.github/workflows/release.yml
GitHub introduced [rulesets](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-rulesets/about-rulesets) last year, a new way to protect branches.
More recently, rulesets now permit to add a `Deploy key` to the bypass list ([doc](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-rulesets/creating-rulesets-for-a-repository#granting-bypass-permissions-for-your-branch-or-tag-ruleset)).
This permits to store the private SSH key of the Deploy key in a [secret](https://docs.github.com/en/actions/security-for-github-actions/security-guides/using-secrets-in-github-actions), and checkout the repository using this key.
After that, the Action can now push on protected branches.
- Make the Action …
=> build: use a deploy key in the release action

cartridges/int_algolia/cartridge/scripts/algolia/helper/deltaIterator.js, cartridges/int_algolia/cartridge/scripts/algolia/helper/fileReadIterator.js, cartridges/int_algolia/cartridge/scripts/algolia/helper/logHelper.js, cartridges/int_algolia/cartridge/scripts/algolia/lib/algoliaConstants.js, cartridges/int_algolia/cartridge/scripts/algolia/steps/algoliaProductDeltaIndex.js
I didn't update the branch before merging #196 on develop and it caused some `no-redeclare` rules to trigger after merging.
=> fix: disable some no-redeclare errors

cartridges/int_algolia_sfra/cartridge/templates/default/algolia/search/searchResultsNoDecorator.isml
- [Minor improvement] Added tabindex="0" to the <a> element (id="articles-tab") to ensure it is keyboard-focusable and included in the natural tabbing order that came with SFRA v7
=> Small accessibility imporvement that comes with SFRA v7

.github/workflows/ci.yml
We use the Conventional Commits syntax in most other places as it forces us to use a meaningful title and make it easier to draft the release notes. Let's enforce it on our repo.
This PR adds a job to our CI workflow, that uses [action-semantic-pull-request](https://github.com/amannn/action-semantic-pull-request) to check the PR title.
=> chore: use action-semantic-pull-request to validate PR title

cartridges/int_algolia/cartridge/scripts/algolia/lib/algoliaProductConfig.js, cartridges/int_algolia/cartridge/scripts/algolia/model/algoliaLocalizedProduct.js, test/mocks/dw/catalog/MasterProduct.js, test/unit/int_algolia/scripts/algolia/helper/__snapshots__/jobHelper.test.js.snap, test/unit/int_algolia/scripts/algolia/model/algoliaLocalizedProduct.test.js, test/unit/int_algolia/scripts/algolia/steps/__snapshots__/algoliaProductDeltaIndex.test.js.snap, test/unit/int_algolia/scripts/algolia/steps/__snapshots__/algoliaProductIndex.test.js.snap
To be compatible with Category Merchandising, we are introducing a new attribute: `categoryPageId`
It follows the official recommendations described in this doc:
https://www.algolia.com/doc/guides/solutions/ecommerce/browse/tutorials/category-pages/#add-a-category-identifying-attribute-to-each-record
The only difference is that instead of using localized paths ("Womens", "Womens > Clothing"), we will use the categories ids:
```
"categoryPageId": [
"womens"
"womens-clothing"
]
```
This permits to keep the same ids across all indices, while still being human readable.
- new `categoryPageId`
- added test
- fixed mocks setup: `newarrivals` category was not marked `online` and was missing from the existing snapshots
---
SFCC-401
=> feat: new categoryPageId attribute

cartridges/int_algolia/cartridge/scripts/algolia/customization/productModelCustomizer.js, cartridges/int_algolia_controllers/cartridge/static/default/js/algolia/instantsearch-config.js, cartridges/int_algolia_controllers/cartridge/templates/default/algolia/productsearchrefinebar.isml, cartridges/int_algolia_sfra/cartridge/static/default/css/algolia/index.css, cartridges/int_algolia_sfra/cartridge/static/default/js/algolia/instantsearch-config.js, cartridges/int_algolia_sfra/cartridge/templates/default/algolia/search/searchResultsNoDecorator.isml, test/unit/int_algolia/scripts/algolia/customization/productModelCustomizer.test.js
Today, we have a `newArrivalsCategory` attribute which contains hierarchical facets.
But displaying two hierarchical facets on the UI can create confusion and duplicates the information:
SFRA default UI uses a "New Arrival" checkbox.
This PR adds a `newArrival` boolean attribute, set to true when a product belongs to the `newarrivals` category, and a [`toggleRefinement`](https://www.algolia.com/doc/api-reference/widgets/toggle-refinement/js/) widget that permits to show a simple refinement checkbox similar to SFRA:
- Refactor the `productModelCustomizer` to also handle the `newArrival` attribute
- Add a `toggleRefinement` widget on the UI, and the CSS to have the same look and feel than SFRA
- Also added to SiteGenesis but with a simpler `labelText` and no custom CSS
- Add `newArrival` to …
=> feat: newArrival attribute

cartridges/int_algolia_controllers/cartridge/static/default/js/algolia/instantsearch-config.js, cartridges/int_algolia_sfra/cartridge/static/default/js/algolia/instantsearch-config.js
InstantSearch panel permits to implement a `hidden` function to determine if the panel should be hidden ([doc](https://www.algolia.com/doc/api-reference/widgets/panel/js/#widget-param-hidden)).
It wasn't working for hierarchicalFacets, and a workaround had been done in  https://github.com/algolia/algoliasearch-sfcc-b2c/pull/146 to try to replicate the logic.
The problem is that when the panel is hidden by this hack, if the selected filters are reset, **it's not becoming visible anymore**.
- fix the `hidden` function: the hierarchicalFacets are always present in `options.results.hierarchicalFacets`. But when there are no results matching, the `data` field is `null`. Checking the presence of `data` fixes the behaviour
- remove the buggy workaround
- Index records with the …
=> fix(frontend): hidding logic wasn't working for hierachicalFacets panel

cartridges/int_algolia/cartridge/scripts/algolia/lib/algoliaProductConfig.js, cartridges/int_algolia/cartridge/scripts/algolia/model/algoliaLocalizedProduct.js, test/unit/int_algolia/scripts/algolia/helper/__snapshots__/jobHelper.test.js.snap, test/unit/int_algolia/scripts/algolia/helper/jobHelper.test.js, test/unit/int_algolia/scripts/algolia/model/algoliaLocalizedProduct.test.js, test/unit/int_algolia/scripts/algolia/steps/__snapshots__/algoliaProductDeltaIndex.test.js.snap, test/unit/int_algolia/scripts/algolia/steps/__snapshots__/algoliaProductIndex.test.js.snap, test/unit/int_algolia/scripts/algolia/steps/algoliaProductIndex.test.js
Today we have the following list of default attributes:
`'name', 'categories', 'primary_category_id', '__primary_category', 'in_stock', 'price', 'image_groups', 'url'`
Some of them are not used by our default UI and are not following Algolia latest guidelines.
We want to replace of remove them:
- replace `categories` by the new `categoryPageId` attribute introduced in #206 
- remove the `primary_category_id` attribute
- remove the undocumented `_tags` attribute: `_tags` are a built-in way to do filtering in Algolia, but ours only contains the product id and are not used
After this PR, the default list of attributes will be:
`'name', 'categoryPageId', '__primary_category', 'in_stock', 'price', 'image_groups', 'url'`
The attribute definitions are kept, so if clients rely on them, they can …
=> feat!: change default attributes

cartridges/int_algolia_sfra/cartridge/static/default/js/algolia/index.js, cartridges/int_algolia_sfra/cartridge/static/default/js/algolia/instantsearch-config.js, cartridges/int_algolia_sfra/cartridge/templates/default/components/header/search.isml
Implement [Category Pages](https://www.algolia.com/doc/guides/solutions/ecommerce/browse/tutorials/category-pages/) using the `categoryPageId` added in #206.
This is done by adding a `filters` on the InstantSearch configuration ([doc](https://www.algolia.com/doc/guides/solutions/ecommerce/browse/tutorials/category-pages/#build-a-user-interface-with-instantsearch-js))
For categories pages, the `hierarchicalMenu` are not displayed anymore. This is on purpose, a category page is a standalone page of a single category.
- Pass the `categoryId` to the `enableInstantSearch` options
- add a `filters` on `categoryPageId` when the `categoryId` is present
- add the hierarchical menus otherwise (if we are on the search results page)
- Remove the `breadcrumb` widget. The category title not be updated …
=> feat(sfra): category pages

cartridges/int_algolia/cartridge/scripts/algolia/model/algoliaLocalizedProduct.js
Updated the `in_stock` handler to utilize the `ProductAvailabilityModel` for better accuracy in determining product availability. The logic now checks the availability status directly for master products and variation groups, and retrieves the inventory record for other products to assess stock levels against the defined threshold.
**Note:**  Should be changed:
```
in_stock: {
localized: false,
variantAttribute: true,
}
```
to:
```
in_stock: {
localized: false,
}
```
To update `in_stock` partially and move it to the record level.
Doc link is here: https://github.com/algolia/doc/pull/9652
=> fix: improve product availability check in algoliaLocalizedProduct.js

cartridges/int_algolia/cartridge/scripts/algolia/lib/algoliaSplitter.js, test/unit/int_algolia/scripts/algolia/lib/algoliaSplitter.test.js
- Refactored `splitHtmlContent` to enhance section trimming and ensure empty sections are properly handled.
- Updated `removeIgnoredContent` to correctly remove multiline content within ignored tags and self-closing tags.
- Added a new test case to verify removal of content inside multiline  tags.
=> fix: improve HTML content handling in algoliaSplitter.js

cartridges/int_algolia_sfra/cartridge/static/default/js/algolia/instantsearch-config.js
Prices were not displayed in Base product indexing mode with the default attributes, i.e. when there wasn't any other price source such as promotions or pricebooks.
There was two mistakes in the `calculateDisplayPrice` function:
- It was returning the `price` attribute as-is, while it can actually be an object with multiple currencies
- It was using `item` instead of `variant`, so when `item` is the base product, `item.price` is undefined
=> fix(sfra): prices were not displayed for product-level indexing

cartridges/bm_algolia/cartridge/controllers/AlgoliaBM.js, cartridges/bm_algolia/cartridge/templates/default/algoliabm/dashboard/index.isml, cartridges/bm_algolia/cartridge/templates/resources/algolia.properties
- Added site preference for managing real-time inventory
**Note**: Next PR [here](https://github.com/algolia/algoliasearch-sfcc-b2c/pull/224).
=> feat: Added Site Preferences/Metadata for real time inventory updates

cartridges/bm_algolia/cartridge/controllers/AlgoliaBM.js, cartridges/bm_algolia/cartridge/templates/default/algoliabm/dashboard/index.isml, cartridges/bm_algolia/cartridge/templates/resources/algolia.properties, cartridges/int_algolia/cartridge/scripts/algolia/model/algoliaLocalizedProduct.js, cartridges/int_algolia_sfra/cartridge/controllers/CheckoutServices.js, cartridges/int_algolia_sfra/cartridge/scripts/hooks.json, cartridges/int_algolia_sfra/cartridge/scripts/hooks/order/afterPOST.js, cartridges/int_algolia_sfra/package.json, metadata/algolia/meta/system-objecttype-extensions.xml, test/unit/int_algolia/scripts/algolia/model/algoliaLocalizedProduct.test.js
- Introduced the `afterPOST` hook to send inventory changes to Algolia upon order completion.
- Refactored store availability retrieval to use `StoreMgr` for consistency and storefront logic.
- Adjusted inventory check logic to include products with ATS values meeting the threshold.
- Update a product inventory with value 1 (or adjust it according to inventory threshold), Disable Index out-of-stock products, after order this product should be deleted
- Update a product inventory with value 1 (or adjust it according to inventory threshold), Enable Index out of stock products, after order this product `in_stock` value should be false
- Update a product's **store** inventory with value 1 (or adjust it according to inventory threshold), after order this product `storeAvailability` array …
=> feat: Implement Hooks for SFRA and Real-Time Inventory Updates for variant level records

cartridges/int_algolia/cartridge/scripts/algolia/filters/productFilter.js, cartridges/int_algolia/cartridge/scripts/algolia/helper/jobHelper.js, cartridges/int_algolia/cartridge/scripts/algolia/helper/orderHelper.js, cartridges/int_algolia/cartridge/scripts/algolia/model/algoliaLocalizedProduct.js, cartridges/int_algolia_sfra/cartridge/controllers/CheckoutServices.js, cartridges/int_algolia_sfra/cartridge/scripts/hooks.json, cartridges/int_algolia_sfra/cartridge/scripts/hooks/order/afterPOST.js, cartridges/int_algolia_sfra/cartridge/scripts/hooks/order/algoliaHooks.js, cartridges/int_algolia_sfra/cartridge/static/default/js/algolia/instantsearch-config.js, jest.setup.js, test/mocks/dw/system/Status.js, test/unit/int_algolia/scripts/algolia/helper/__snapshots__/jobHelper.test.js.snap, test/unit/int_algolia/scripts/algolia/helper/__snapshots__/orderHelper.test.js.snap, test/unit/int_algolia/scripts/algolia/helper/jobHelper.test.js, test/unit/int_algolia/scripts/algolia/helper/orderHelper.test.js, test/unit/int_algolia/scripts/algolia/helper/productFilter.test.js, test/unit/int_algolia/scripts/algolia/model/algoliaLocalizedProduct.test.js, test/unit/int_algolia/scripts/hooks/order/__snapshots__/algoliaHooks.test.js.snap, test/unit/int_algolia/scripts/hooks/order/algoliaHooks.test.js
- Added realtime inventory updates support for master level
- Added `generateAlgoliaOperations` function in `orderHelper.js` to create Algolia operations for product updates based on order shipments.
- For **in-store pickup (BOPIS)** orders, it utilizes the new `isInStoreStock` function to check store-specific inventory and updates store availability accordingly.
- Updated `afterPOST` hook in `afterPOST.js` to handle in-store and standard shipment processing, utilizing the new helper functions for inventory checks and Algolia operations.
- Refactored existing logic for clarity, modularity and maintainability, ensuring consistent handling of product availability updates in Algolia.
=> feat: Enhanced realtime inventory updates for master record model

.github/workflows/ci.yml, cartridges/int_algolia/cartridge/configuration/productFilterConfig.example.js, cartridges/int_algolia/cartridge/scripts/algolia/filters/productFilter.js, cartridges/int_algolia/cartridge/scripts/algolia/steps/algoliaProductDeltaIndex.js, test/unit/int_algolia/scripts/algolia/helper/productFilter.test.js
- Created a new config file to manage how the new filter mechanism that was introduced behaves in #228.
- Added another case for #228 that prevented removing offline products from search for delta indexes.
- Used macOS resources for CI flow to make browser tests more stable.
Rename `productFilterConfig.example.js` to `productFilterConfig.js`, and just change boolean values to manage filter mechanism behavior.
=> feat: Customizable filter mechanism
